[book]
authors = ["Borna Šoštarić"]
language = "en"
src = "src"
title = "PocketLibs Documentation"

[output.html]
preferred-dark-theme = "dark"
additional-css = ["./tasklist.css"]

[preprocessor.alerts]
