name: docs

on:
  push:
    paths: ["docs/**"]
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-mdbook-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-mdbook-

      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: build graphs
        run: cd docs && bash ./build-graphs.sh

      - name: Install mdbook
        run: cargo install mdbook --version 0.4.52 --locked

      - name: Install mdbook-alerts
        run: cargo install mdbook-alerts --version 0.8.0 --locked

      - name: Build docs
        run: cd docs && mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/book

  deploy-docs:
    needs: build-docs
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
